# Generated by Django 2.2.13 on 2021-05-03 12:51

import FABRIQUE_POLLS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, validators=[FABRIQUE_POLLS.models.QuestionValidator])),
                ('text', models.CharField(max_length=300)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FABRIQUE_POLLS.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(db_index=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FABRIQUE_POLLS.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FABRIQUE_POLLS.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30, validators=[FABRIQUE_POLLS.models.QuestionValidator])),
                ('question_text', models.CharField(max_length=300)),
                ('answer_text', models.CharField(max_length=300)),
                ('finished_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FABRIQUE_POLLS.Finished_poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FABRIQUE_POLLS.Question')),
            ],
        ),
    ]
